const Data = [
    {
      imageUrl: [nda],
      title: "NDA",
      description: "Protect your Business, ideas and future projects !",
      time: "2 min",
      signed: "0 signed",
    },
    {
      imageUrl: [cdi],
      title: "CDI, CDD, CIVP",
      description: "Keep your business and work safe with E-Tafakna.",
      time: "3 min",
      signed: "0 signed",
    },
    {
      imageUrl: [freelance],
      title: "Freelancer",
      description: "Give your side hustle some protection !",
      time: "5 min",
      signed: "0 signed",
    },
    {
      imageUrl: [Referral],
      title: "Loan request form",
      description: "Asking for a loan ? E-Tafakna.",
      time: "1 min",
      signed: "0 signed",
    },
    {
      imageUrl: [pret],
      title: "Loan agreement",
      description: "Protect yourself when lending money",
      time: "3 min",
      signed: "0 signed",
    },
    {
      imageUrl: [assurance],
      title: "Travel insurance",
      description: "I don’t want to go to my insurer to get my travel insurance contract before traveling ! Go to E-Tafakna.",
      time: "2 min",
      signed: "0 signed",
    },
    {
      imageUrl: [devis],
      title: "Order form quotation bill",
      description: "A fast way to fill an order form, quotation or a bill ? E-Tafakna.",
      time: "1 min",
      signed: "0 signed",
    },
    {
      imageUrl: [partenariat],
      title: "Partnership and engagement ",
      description: "Written agreements make the best partnerships!",
      time: "4 min",
      signed: "0 signed",
    },
    {
      imageUrl: [salepurchase],
      title: "Purchase and sale",
      description: "Secure your right to buy and sell !",
      time: "4 min",
      signed: "0 signed",
    },
    {
      imageUrl: [vente],
      title: "House rental",
      description: "Rent your room, apartment or house with E-Tafakna",
      time: "1 min",
      signed: "0 signed",
    },
    {
      imageUrl: [carbying],
      title: "Car rental and purchase",
      description: "It’s safer to rent or buy a car with E-Tafakna",
      time: "3 min",
      signed: "0 signed",
    },
    {
      imageUrl: [domiciliation],
      title: "Business domiciliation",
      description: "Tell us where are you receiving all your legal documents",
      time: "2 min",
      signed: "0 signed",
    },
  ];
  export default Data